#默认使用配置
spring:
 profiles:
  active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.com.example.demo.entity
#  mapperLocations: classpath:mapper/*.xml    #当mybatis的xml文件和mapper接口不在相同包下时，需要用mapperLocations属性指定xml文件的路径
---
#开发配置
spring:
 profiles: dev

 datasource:
   url: jdbc:oracle:thin:@120.195.40.209:10521:orcl
   username: xxxx
   password: xxxx
   driver-class-name: oracle.jdbc.OracleDriver
   # 使用druid数据源
   #type: com.alibaba.druid.pool.DruidDataSource

 thymeleaf:
  enabled: true  #开启thymeleaf视图解析
  encoding: utf-8  #编码
  prefix: classpath:/templates/  #前缀
  cache: false  #是否使用缓存
  mode: HTML  #严格的HTML语法模式
  suffix: .html  #后缀名

